### ISSUE TITLE
Package does not compile due to potential mismatch of "require" and "import" syntax

### ISSUE THREAD

**Issue by mmartinezluis** [mauriciopoppe/function-plot#278]
I'm using Nextjs V12. When trying to use the function-plot library via import statement, the library does not work. I get the below error:

<img width="1159" alt="isse_compiling" src="https://github.com/mauriciopoppe/function-plot/assets/75151961/1157249d-9c63-46c7-8489-dd6b4a986c43">

There seems to be an import mismatch between the d3-shape dependency and the chart.js dependency. I would appreciate help on solving this issue.

**Comment by mauriciopoppe** [comment]
Thanks for the report, which version of function-plot are you using?

**Comment by mmartinezluis** [comment]
I'm using the latest version, 1.24.4

**Comment by mauriciopoppe** [comment]
I think it's happening because the dist files in `dist/` emitted in v1.24.4 use CommonJS and the d3-* libraries use JS modules. So the flow is: JS Module (your app) -> CommonJS (function plot) -> JS Module (d3)

As a workaround try this import which uses a bundled version of function-plot which is the entire library in a single file:

```javascript
import functionPlot from 'function-plot/dist/function-plot'
```

---

For the real solution the flow above needs to be JS Module (your app) -> JS Modlue (function plot) -> JS Module (d3). I switched to use JS modules in the master branch so you should be able to do `import functionPlot from 'function-plot'` in a future release.

**Comment by mmartinezluis** [comment]
Thank you for the response. I tried the work around, ti does not work:
<img width="1104" alt="error on importing library" src="https://github.com/mauriciopoppe/function-plot/assets/75151961/0d6921f0-828a-4946-8857-9c5166ad4066">

<img width="935" alt="error on importing library terminal" src="https://github.com/mauriciopoppe/function-plot/assets/75151961/466b9708-dd66-4c12-a887-aff487ff7da0">

It seems that this is a breaking change.

**Comment by mmartinezluis** [comment]
Since the documentaiton for Function-plot is solely written using JS Module syntax (and hence the users of Function-plot are more likely using ESM imports), I think that a new release for this seemingly breaking change should not be that difficult, given that you already updated the master branch for chart.js. I'll be looking forward to the release/fix. Thank you.

**Comment by mauriciopoppe** [comment]
I tried the following in a hello world parcel app and it did work:

```javascript 
import functionPlot from 'function-plot/dist/function-plot'

functionPlot({
  target: '#playground',
  data: [{ fn: 'x^2', graphType: 'polyline' }]
})
```

I suspect this might be a problem between the integration of the NextJS bundler and this library.

---

There's a dev build not ready for production usage that already uses JS modules, could you please try with this module? `npm install function-plot@1.25.0-0`

**Comment by mauriciopoppe** [comment]
Related issue in a NextJS app https://github.com/mauriciopoppe/function-plot/issues/278

**Comment by mauriciopoppe** [comment]
I've reproduced this issue with the following steps:

- Follow this guide https://vercel.com/guides/create-hello-world-react-app-nextjs to create a hello world app
- Install function-plot v1.24.4
- Case 1: with the following setup I see the following error

```javascript
import functionPlot from "function-plot";
```
```
⨯ ./node_modules/function-plot/dist/chart.js:7:19
Module not found: ESM packages (d3-shape) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/function-plot/dist/index.js
./src/app/page.js
```

- Case 2: if `src/app/page.js` look like this:

```javascript
import functionPlot from "function-plot/dist/function-plot";
```
```
⨯ node_modules/function-plot/dist/function-plot.js (1:205) @ self
 ⨯ ReferenceError: self is not defined
    at eval (webpack-internal:///(rsc)/./node_modules/function-plot/dist/function-plot.js:4:3)
    at (rsc)/./node_modules/function-plot/dist/function-plot.js (/private/var/folders/c1/clfklx952gg7v4tjck2t8j640000gn/T/tmp.TNCiGCJfdr/hello-world/.next/server/vendor-chunks/function-plot.js:20:1)
    at __webpack_require__ (/private/var/folders/c1/clfklx952gg7v4tjck2t8j640000gn/T/tmp.TNCiGCJfdr/hello-world/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.js:9:90)
    at (rsc)/./src/app/page.js (/private/var/folders/c1/clfklx952gg7v4tjck2t8j640000gn/T/tmp.TNCiGCJfdr/hello-world/.next/server/app/page.js:194:1)
    at Function.__webpack_require__ (/private/var/folders/c1/clfklx952gg7v4tjck2t8j640000gn/T/tmp.TNCiGCJfdr/hello-world/.next/server/webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by mauriciopoppe** [comment]
Thanks for the investigation, yes I saw a similar answer online, in addition I had to make a few changes to the dependencies included.

Anyways, first install the latest alpha version (not production ready yet) `npm install function-plot@alpha`.

The toy app I have looks like this:

```javascript
"use client";

import React, { useRef, useEffect } from "react";
import functionPlot from "function-plot";
import styles from "./page.module.css";

export const FunctionPlot = React.memo(
  ({ options }) => {
    const rootEl = useRef(null);
    useEffect(() => {
      try {
        functionPlot(Object.assign({}, options, { target: rootEl.current }));
      } catch (e) {}
    });
    return <div ref={rootEl} />;
  },
  () => false,
);

export default function Home() {
  const options = {
    data: [{ fn: "x^2", graphType: "polyline" }],
  };
  return (
    <main className={styles.main}>
      <FunctionPlot options={options} />
    </main>
  );
}
```

**Comment by mmartinezluis** [comment]
Hi Mauricio,

Thank you for the code. I just tested the code, and it shows an error:

**Comment by SnowyField1906** [comment]
it has been a month and will there any update for this in near future?

**Comment by mauriciopoppe** [comment]
I tried the changes in https://github.com/mauriciopoppe/function-plot/issues/278#issuecomment-1943097069 and they work for me, here's my setup:

```sh
cd $(mktemp -d)
npm init -y
npx create-next-app@latest
cd my-app
npm install function-plot@2.0.0-0
cat <<EOF > src/app/page.js
"use client";

import React, { useRef, useEffect } from "react";
import functionPlot from "function-plot";
import styles from "./page.module.css";

export const FunctionPlot = React.memo(
  ({ options }) => {
    const rootEl = useRef(null);
    useEffect(() => {
      try {
        functionPlot(Object.assign({}, options, { target: rootEl.current }));
      } catch (e) {}
    });
    return <div ref={rootEl} />;
  },
  () => false,
);

export default function Home() {
  const options = {
    data: [{ fn: "x^2", graphType: "polyline" }],
  };
  return (
    <main className={styles.main}>
      <FunctionPlot options={options} />
    </main>
  );
}
EOF
npm run dev
```

When I open the dev webpage I see no errors 
<img width="739" alt="image" src="https://github.com/mauriciopoppe/function-plot/assets/1616682/0904ac5f-3830-4f6c-a98a-8104f97b31c5">

**Comment by Linho1219** [comment]
Any follow-up on this issue? I encountered the same problem when using it in my Vitepress project. The dev server runs fine, but the build fails. I have tried the previous methods, and using `import functionPlot from 'function-plot/dist/function-plot'` results in another error: 
```
ReferenceError: self is not defined
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async build (node_modules/vitepress/dist/node/serve-4DnZ8_Si.js:48721:24)
Node.js v20.15.1
```
Using v1.25.0.

**Comment by Linho1219** [comment]
Based on the error message, the problematic package seems to be `web-worker`. So, I found it in `interval_worker_pool.ts` and tried commenting out the `import Worker from 'web-worker'`. Surprisingly, this resolved the issue.

I looked into it and found that the `web-worker` package implemented atop Node's worker_threads, while in the browser, it's merely an alias for `Worker`. Since `function-plot` runs in the browser, I believe it's safe to remove this package to solve the problem.

**Comment by mauriciopoppe** [comment]
I checked that I'm using `web-workers` on the node side to do a few perf tests, however it was possible to use different implementations depending on where parts of the program are running. Through #320 `web-worker` is no longer a browser dependency.
